/**
 * ⚠️  AUTO-GENERATED — DO NOT EDIT MANUALLY.
 *
 * Source: docfilling-syntax/docfilling_syntax/validator.py
 * Generator: scripts/gen-ts.py
 *
 * Re-generate with:  python scripts/gen-ts.py
 */

import { TYPO_PATTERNS, SYSTEM_FIELDS } from "./constants";
// ⚠️ PARCHE A MANO — NO QUITAR AL REGENERAR CON gen-ts.py.
import { parseComparacion, parseNumero } from "./comparar";
// ⚠️ Import añadido a mano — no quitar al regenerar (ver declare-types.ts).
import { tipoAceptado, tipoCanonico } from "./declare-types";
import { parseFields, FieldType, offsetToLineCol, type ParsedField } from "./parser";

// =============================================================================
// Types
// =============================================================================

export enum Severity {
  ERROR = "error",
  WARNING = "warning",
  INFO = "info",
}

export interface DiagnosticFix {
  title: string;
  from?: { line: number; col: number };
  to?: { line: number; col: number };
  replacement: string;
}

export interface Diagnostic {
  line: number;
  col: number;
  endLine: number;
  endCol: number;
  severity: Severity;
  code: string;
  message: string;
  fix?: DiagnosticFix;
  /** Source file path — set for diagnostics from resolved INCLUDE files.
   *  Not generated by validateText(); added manually when validating includes.
   *  NOTE: added manually — do not remove when regenerating from gen-ts.py. */
  filePath?: string;
}

export interface ValidationResult {
  diagnostics: Diagnostic[];
  fieldsFound: number;
}

// =============================================================================
// Helper
// =============================================================================

function diag(
  line: number,
  col: number,
  length: number,
  sev: Severity,
  code: string,
  msg: string,
): Diagnostic {
  return {
    line,
    col,
    endLine: line,
    endCol: col + length,
    severity: sev,
    code,
    message: msg,
  };
}

// =============================================================================
// Rule: Syntax errors (malformed braces)
// =============================================================================

function checkSyntaxErrors(text: string, result: ValidationResult): void {
  // Single-pass brace walker — multi-line directives are valid.
  // Emits E001 (unclosed at EOF), E001b (re-opened before close /
  // literal nesting), E001c (orphan closing).
  const stack: number[] = [];
  const reBrace = /\{\{|\}\}/g;
  let bm: RegExpExecArray | null;
  while ((bm = reBrace.exec(text)) !== null) {
    const offset = bm.index;
    const token = bm[0];
    if (token === "{{") {
      if (stack.length > 0) {
        const prev = stack.pop()!;
        const [pl, pc] = offsetToLineCol(text, prev);
        const d = diag(pl, pc, 2, Severity.ERROR, "E001b",
          "Placeholder '{{' reabierto sin cerrar el anterior");
        result.diagnostics.push(d);
      }
      stack.push(offset);
    } else {
      if (stack.length === 0) {
        const [l, c] = offsetToLineCol(text, offset);
        const d = diag(l, c, 2, Severity.ERROR, "E001c",
          "Cierre '}}' sin apertura");
        result.diagnostics.push(d);
      } else {
        stack.pop();
      }
    }
  }
  if (stack.length > 0) {
    const [eofLine, eofCol] = offsetToLineCol(text, text.length);
    for (const offset of stack) {
      const [l, c] = offsetToLineCol(text, offset);
      const d = diag(l, c, 2, Severity.ERROR, "E001",
        "Placeholder '{{' sin cerrar");
      d.fix = {
        title: "Cerrar con }}",
        from: { line: eofLine, col: eofCol },
        to: { line: eofLine, col: eofCol },
        replacement: "}}",
      };
      result.diagnostics.push(d);
    }
  }

  // Single-brace lookalike: {FIELD} — line-local check.
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineNum = i + 1;
    const reSingle = /(?<!\{)\{(?!\{)([a-zA-Z_][\w\u00C0-\u024F]*)\}(?!\})/g;
    let rm: RegExpExecArray | null;
    while ((rm = reSingle.exec(line)) !== null) {
      const d = diag(
        lineNum,
        rm.index + 1,
        rm[0].length,
        Severity.WARNING,
        "W001",
        `Llave simple '{${rm[1]}}' — ¿falta una llave? Quizá debería ser '{{${rm[1]}}}'`,
      );
      d.fix = {
        title: `Convertir a {{${rm[1]}}}`,
        replacement: `{{${rm[1]}}}`,
      };
      result.diagnostics.push(d);
    }
  }
}

// =============================================================================
// Rule: Typo detection
// =============================================================================

function checkTypos(text: string, result: ValidationResult): void {
  // Multi-line aware: scan the full text; map offset → (line, col).
  for (const [typoRe, correct] of Object.entries(TYPO_PATTERNS)) {
    // [^}]* matches any char except }; in JS we need /s for newlines.
    const re = new RegExp("\\{\\{[^}]*" + typoRe, "gis");
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
      const [line, col] = offsetToLineCol(text, m.index);
      const d = diag(
        line,
        col,
        m[0].length,
        Severity.WARNING,
        "W002",
        `Posible typo: '${m[0]}' — ¿debería ser '${correct}'?`,
      );
      d.fix = {
        title: `Corregir a '${correct}'`,
        replacement: m[0].replace(new RegExp(typoRe, "i"), correct),
      };
      result.diagnostics.push(d);
    }
  }
}

// =============================================================================
// Rule: Balanced conditionals
// =============================================================================

// Phase 4 — classify a conditional field's raw content
type CondKind = "IF" | "ELSE" | "ENDIF";
function classifyConditional(content: string): { kind: CondKind | null; name: string | null } {
  const upper = content.trim().toUpperCase();
  if (upper === "ENDIF") return { kind: "ENDIF", name: null };
  // ⚠️ PARCHE A MANO — NO QUITAR AL REGENERAR CON gen-ts.py.
  // `{{END IF}}` / `{{END_IF}}` cierran igual que `{{ENDIF}}` (ver parser).
  if (/^END[\s_]+IF$/.test(upper)) return { kind: "ENDIF", name: null };
  if (upper === "ELSE") return { kind: "ELSE", name: null };
  // Field-name shape allows an optional `SYSTEM:` namespace prefix —
  // legacy `{{ENDIF_SYSTEM:COMUNIDAD}}` and friends classify properly.
  let m = upper.match(/^ENDIF[_\s]+((?:SYSTEM:)?[\w.\u00C0-\u024F]+)$/);
  if (m) return { kind: "ENDIF", name: m[1] };
  m = upper.match(/^ELSE[_\s]+((?:SYSTEM:)?[\w.\u00C0-\u024F]+)$/);
  if (m) return { kind: "ELSE", name: m[1] };
  if (/^IF\s+/.test(upper)) return { kind: "IF", name: null };
  m = upper.match(/^IF_((?:SYSTEM:)?[\w.\u00C0-\u024F]+)/);
  if (m) return { kind: "IF", name: m[1] };
  return { kind: null, name: null };
}

// Phase 4.5 — stack-based balance check (replaces count-based).
function checkBalancedConditionals(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  // Frame: { opener, name (null for canonical), inElse }
  const stack: Array<{ opener: ParsedField; name: string | null; inElse: boolean }> = [];

  for (const f of fields) {
    if (f.fieldType !== FieldType.CONDITIONAL) continue;
    const { kind, name } = classifyConditional(f.content);
    if (kind === null) continue;

    if (kind === "IF") {
      stack.push({ opener: f, name, inElse: false });
      continue;
    }
    if (kind === "ELSE") {
      if (stack.length === 0) {
        const suffix = name ? `_${name}` : "";
        const d = diag(f.line, f.col, f.raw.length, Severity.ERROR, "E012",
          `ELSE${suffix} sin IF correspondiente`);
        d.fix = { title: `Eliminar ${f.raw}`, replacement: "" };
        result.diagnostics.push(d);
        continue;
      }
      const top = stack[stack.length - 1];
      top.inElse = true;
      if (name !== null && top.name !== null && name !== top.name) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.ERROR, "E016",
            `ELSE_${name} no cierra IF_${top.name} (anidación cruzada)`),
        );
      }
      continue;
    }
    // ENDIF
    if (stack.length === 0) {
      const suffix = name ? `_${name}` : "";
      const d = diag(f.line, f.col, f.raw.length, Severity.ERROR, "E011",
        `ENDIF${suffix} sin IF correspondiente`);
      d.fix = { title: `Eliminar ${f.raw}`, replacement: "" };
      result.diagnostics.push(d);
      continue;
    }
    const popped = stack.pop()!;
    if (name !== null && popped.name !== null && name !== popped.name) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.ERROR, "E016",
          `ENDIF_${name} cierra IF_${popped.name} (anidación cruzada)`),
      );
    }
  }

  for (const frame of stack) {
    const suffix = frame.name ? `_${frame.name}` : "";
    const endif = `ENDIF${suffix}`;
    const d = diag(frame.opener.line, frame.opener.col, frame.opener.raw.length,
      Severity.ERROR, "E010",
      `IF${suffix} sin ENDIF correspondiente`);
    d.fix = {
      title: `Insertar {{${endif}}}`,
      from: { line: frame.opener.line, col: frame.opener.col + frame.opener.raw.length },
      to: { line: frame.opener.line, col: frame.opener.col + frame.opener.raw.length },
      replacement: `\n{{${endif}}}`,
    };
    result.diagnostics.push(d);
  }
}

// Phase 4.4 — W080 deprecation warning for legacy IF_X / ELSE_X / ENDIF_X form.
function checkLegacyConditionalForm(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.CONDITIONAL) continue;
    const { kind, name } = classifyConditional(f.content);
    if (kind === null || name === null) continue;
    let canonical: string;
    let msg: string;
    if (kind === "IF") {
      canonical = `{{IF ${name}}}`;
      msg = `Forma legacy {{IF_${name}}} obsoleta — prefiera ${canonical}`;
    } else if (kind === "ELSE") {
      canonical = "{{ELSE}}";
      msg = `Forma legacy {{ELSE_${name}}} obsoleta — prefiera ${canonical}`;
    } else {
      canonical = "{{ENDIF}}";
      msg = `Forma legacy {{ENDIF_${name}}} obsoleta — prefiera ${canonical}`;
    }
    const d = diag(f.line, f.col, f.raw.length, Severity.WARNING, "W080", msg);
    d.fix = { title: `Migrar a ${canonical}`, replacement: canonical };
    result.diagnostics.push(d);
  }
}

// =============================================================================
// Rule (Phase 5.1): canonical INCLUDE form
// =============================================================================

// Phase 5.1 — W081: prefer canonical {{INCLUDE name}} over alt forms.
function checkIncludeForm(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.INCLUDE) continue;
    const upper = f.content.toUpperCase().trim();
    if (!upper.startsWith("INCLUDE")) continue;
    const rest = upper.slice("INCLUDE".length);
    if (rest.startsWith(" ")) continue; // canonical
    if (!f.includeTarget) continue;
    const canonical = `{{INCLUDE ${f.includeTarget}}}`;
    const d = diag(f.line, f.col, f.raw.length, Severity.WARNING, "W081",
      `Forma no canónica de INCLUDE — prefiera ${canonical}`);
    d.fix = { title: `Migrar a ${canonical}`, replacement: canonical };
    result.diagnostics.push(d);
  }
}

// =============================================================================
// Rule: el NOMBRE del INCLUDE se cortó (E031) y su destino no existe (E030)
// =============================================================================

/**
 * ⚠️ E031 — EL NOMBRE SE CORTÓ EN UN CARÁCTER QUE EL PARSER NO ADMITE.
 *
 * `INCLUDE_PATTERN` acepta `[\p{L}\p{N}_]`, así que `{{INCLUDE VAR_TERMINADA_28-1}}`
 * se lee como `VAR_TERMINADA_28` y `{{INCLUDE VAR_OBRA_NUEVA.md}}` como
 * `VAR_OBRA_NUEVA`. El Python tenía `(\w+)`: el mismo agujero.
 *
 * Esto NO es teórico y es la razón de que esta regla exista. Medido en la
 * biblioteca el 5-oct-2026: **14 esquemas de obra nueva y demolición no se
 * podían generar** porque sus `VAR_*_28-1` se buscaban como `VAR_*_28`, y otros
 * 16 INCLUDE escribían el nombre con `.md`. El fichero estaba delante, con el
 * nombre correcto, y el único síntoma era un «párrafo no encontrado» al cargar
 * la biblioteca — nada en el editor.
 *
 * Se avisa SIN necesidad de la biblioteca: basta comparar lo que el parser leyó
 * con lo que hay escrito. Y se ofrece el arreglo, que es calculable.
 */
function checkIncludeNombreCortado(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.INCLUDE || !f.includeTarget) continue;
    const i = f.content.toUpperCase().indexOf(f.includeTarget.toUpperCase());
    if (i < 0) continue;
    const tras = f.content.slice(i + f.includeTarget.length);
    // Sólo cuenta lo que PARECE seguir siendo el nombre: un guion, un punto o
    // más letras. Las formas no canónicas —paréntesis, comillas— ya las avisa
    // W081, y confundirlas aquí daría dos avisos por lo mismo.
    const m = /^[-.][\p{L}\p{N}_.-]*/u.exec(tras.trim());
    if (!m) continue;
    const completo = f.includeTarget + m[0];
    const limpio = completo.replace(/\.md$/i, '').replace(/-/g, '_');
    const d = diag(f.line, f.col, f.raw.length, Severity.ERROR, "E031",
      `El nombre del INCLUDE se corta en «${m[0][0]}»: se buscará `
      + `'${f.includeTarget}' y no '${completo}'. Los nombres de párrafo sólo `
      + `admiten letras, números y _`);
    // Se compara con lo ESCRITO, no con lo que el parser leyó: quitar un `.md`
    // deja el mismo destino —ya se leía sin él— y sin embargo el arreglo es
    // justo ése, cambiar el texto para que diga lo que significa.
    if (limpio !== completo) {
      d.fix = { title: `Usar ${limpio}`, replacement: `{{INCLUDE ${limpio}}}` };
    }
    result.diagnostics.push(d);
  }
}

/**
 * E030 — el `{{INCLUDE}}` apunta a un párrafo que NO EXISTE.
 *
 * Sólo se puede comprobar con la biblioteca delante, así que depende del
 * `resolver`: sin él no se dice nada (no hay forma de saberlo, y un falso
 * positivo en el editor enseñaría a ignorar los avisos).
 *
 * Es ERROR y no aviso porque un INCLUDE que no resuelve **se lleva su cláusula**:
 * el motor deja en su lugar «[Párrafo 'X' no encontrado]» y lo que no se vea
 * acaba en la escritura. Hasta hoy esto sólo salía al cargar la biblioteca
 * entera —61 de 105 esquemas lo tenían— y nunca en el editor, que es donde se
 * escribe el INCLUDE.
 */
function checkIncludeDestinoExiste(
  fields: ParsedField[],
  resolver: IncludeResolver,
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.INCLUDE || !f.includeTarget) continue;
    if (resolver(f.includeTarget)) continue;
    result.diagnostics.push(
      diag(f.line, f.col, f.raw.length, Severity.ERROR, "E030",
        `El párrafo '${f.includeTarget}' no existe en la biblioteca: esta `
        + `cláusula desaparecerá del documento`),
    );
  }
}

// =============================================================================
// Rule (Phase 5.2): COMMENT_BEGIN/COMMENT_END deprecation
// =============================================================================

// Phase 5.2 — W083: deprecate {{COMMENT_BEGIN}}/{{COMMENT_END}}.
function checkCommentBlockForm(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    const upper = f.content.toUpperCase().trim();
    if (upper.startsWith("COMMENT_BEGIN") || upper.startsWith("COMMENT_END")) {
      const d = diag(f.line, f.col, f.raw.length, Severity.WARNING, "W083",
        `Forma deprecada \`{{${f.content.trim()}}}\` — prefiera \`{{COMMENT: …}}\` (admite saltos de línea)`);
      d.fix = { title: "Migrar a {{COMMENT: …}}", replacement: "{{COMMENT: }}" };
      result.diagnostics.push(d);
    }
  }
}

// =============================================================================
// Rule: INPUT syntax
// =============================================================================

function checkInputSyntax(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.INPUT && f.fieldType !== FieldType.INPUT_FINAL)
      continue;

    if (!f.name) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.ERROR, "E020",
          "Campo INPUT sin nombre de campo"),
      );
    }
    if (!f.inputDescription) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W020",
          `Campo INPUT '${f.name}' sin descripción`),
      );
    }
    if (f.content.includes("|") && f.inputOptions.length === 0) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W021",
          `Campo INPUT '${f.name}' tiene '|' pero sin opciones válidas`),
      );
    }
  }
}

// =============================================================================
// Rule: DEPENDENCY syntax
// =============================================================================

function checkDependencySyntax(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.DEPENDENCY) continue;

    if (!f.depName) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W030",
          "DEPENDENCY sin nombre de ley"),
      );
    }
    if (!f.depUrl) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W031",
          `DEPENDENCY '${f.depName}' sin URL`),
      );
    } else if (
      !f.depUrl.startsWith("http://") &&
      !f.depUrl.startsWith("https://")
    ) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W032",
          `DEPENDENCY '${f.depName}' URL no parece válida: ${f.depUrl}`),
      );
    }
  }
}

// =============================================================================
// Rule: AUTO syntax
// =============================================================================

function checkAutoSyntax(
  fields: ParsedField[],
  allFieldNames: Set<string>,
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.AUTO) continue;

    if (f.autoOptions.length < 2) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.ERROR, "E040",
          `AUTO requiere al menos 2 opciones, encontrada(s) ${f.autoOptions.length}: '${f.content}'`),
      );
    }
    for (let i = 0; i < f.autoOptions.length; i++) {
      if (!f.autoOptions[i].trim()) {
        const d = diag(f.line, f.col, f.raw.length, Severity.WARNING, "W040",
          `AUTO opción ${i + 1} vacía en '${f.content}'`);
        d.fix = {
          title: "Eliminar opciones vacías",
          replacement: f.raw.replace(/\|{2,}/g, "|"),
        };
        result.diagnostics.push(d);
      }
    }
    if (f.autoHint && !allFieldNames.has(f.autoHint.toUpperCase())) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W041",
          `AUTO hint '(${f.autoHint})' no corresponde a ningún campo conocido en el archivo`),
      );
    }
  }
}

// =============================================================================
// Rule: Duplicate definitions
// =============================================================================

function checkDuplicateDefinitions(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  // 1. Duplicate DECLARE / DECLARE_ARRAY directives — Phase 7.1: shared namespace.
  const declareSeen: Record<string, ParsedField> = {};
  for (const f of fields) {
    if ((f.fieldType === FieldType.DECLARE || f.fieldType === FieldType.DECLARE_ARRAY) && f.name) {
      const key = f.name.toUpperCase();
      if (key in declareSeen) {
        const first = declareSeen[key];
        const kind = f.fieldType === FieldType.DECLARE_ARRAY ? "DECLARE ARRAY" : "DECLARE";
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.ERROR, "E050",
            `Definición duplicada: ${kind} ${f.name} ya existe en línea ${first.line}`),
        );
      } else {
        declareSeen[key] = f;
      }
    }
  }

  // 2. Contradictory extraction instructions for EXTRACTED fields
  const extractionInstructions: Record<string, { instr: string; field: ParsedField }> = {};
  for (const f of fields) {
    if (f.fieldType === FieldType.EXTRACTED && f.name && f.content) {
      const m = f.content.match(/\[([^\]]+)\]/);
      if (m) {
        const instr = m[1];
        const key = f.name.toUpperCase();
        if (key in extractionInstructions) {
          const prev = extractionInstructions[key];
          if (instr !== prev.instr) {
            result.diagnostics.push(
              diag(f.line, f.col, f.raw.length, Severity.ERROR, "E050",
                `Instrucciones de extracción contradictorias para '${f.name}': [${prev.instr}] vs [${instr}]`),
            );
          }
        } else {
          extractionInstructions[key] = { instr, field: f };
        }
      }
    }
  }
}

// =============================================================================
// Rule: DECLARE syntax (AS TYPE and fixed-value constraints)
// =============================================================================

// ⚠️ PARCHE A MANO — NO QUITAR AL REGENERAR CON gen-ts.py.
// Los tipos y sus sinónimos viven en `declare-types.ts` (fuente única). El
// Python sólo admite los cuatro canónicos; desde el 2-oct-2026 este paquete
// evoluciona libre (D25 del plan) y acepta sinónimos obvios como BOOLEAN,
// NUMBER o STRING, que la biblioteca real usa en 4 ficheros.
const DECLARE_TYPES = new Set(["BOOL", "TEXT", "NUM", "DATE"]);

function checkDeclareSyntax(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.DECLARE) continue;

    // E051: AS TYPE must be a known type (canónico o sinónimo — ver
    // `declare-types.ts`; parche a mano, no quitar al regenerar).
    if (f.declareType && !tipoAceptado(f.declareType)) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.ERROR, "E051",
          `Tipo DECLARE inválido '${f.declareType}'. Válidos: ${[...DECLARE_TYPES].sort().join(", ")}`),
      );
      continue;
    }
    // W051: AS BOOL value must be TRUE or FALSE
    if (tipoCanonico(f.declareType) === "BOOL" && f.declareValue) {
      if (f.declareValue.toUpperCase() !== "TRUE" && f.declareValue.toUpperCase() !== "FALSE") {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W051",
            `DECLARE ${f.name} AS BOOL: valor '${f.declareValue}' no es TRUE ni FALSE`),
        );
      }
    }
    // W052: AS NUM value must be numeric
    if (tipoCanonico(f.declareType) === "NUM" && f.declareValue) {
      if (isNaN(Number(f.declareValue))) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W052",
            `DECLARE ${f.name} AS NUM: valor '${f.declareValue}' no es numérico`),
        );
      }
    }
    // W053: :OPTIONS(...) declared but the option list is empty.
    if (
      f.extractionOptions != null &&
      f.content.toUpperCase().replace(/ /g, "").includes(":OPTIONS(")
    ) {
      if (f.extractionOptions.length === 0) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W053",
            `DECLARE ${f.name}: :OPTIONS(...) está vacío — añade al menos un valor`),
        );
      }
    }
    // W054: default value not present in OPTIONS list.
    if (
      f.extractionOptions.length > 0 &&
      f.inputDefault &&
      !f.extractionOptions.includes(f.inputDefault)
    ) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W054",
          `DECLARE ${f.name}: valor por defecto '${f.inputDefault}' no está en :OPTIONS(${f.extractionOptions.join(", ")})`),
      );
    }
    // W055: malformed DECLARE — parser fell back to name-only.
    // Surface the residue so silent typos like `;INPUT(` (instead
    // of `:INPUT(`) become a visible warning rather than landing
    // in the wizard stripped of metadata.
    if (f.malformedResidue) {
      const residue = f.malformedResidue;
      const m = residue.match(/^;\s*(INPUT(?:_FINAL)?|OPTIONS|DEFAULT)\b/i);
      let hint: string;
      if (m) {
        hint = ` — ¿quisiste decir ':${m[1].toUpperCase()}('? (usaste ';' en vez de ':')`;
      } else {
        const short = residue.length <= 60 ? residue : residue.slice(0, 57) + "...";
        hint = ` — cola no reconocida: '${short}'`;
      }
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W055",
          `DECLARE ${f.name}: directiva malformada${hint}`),
      );
    }
  }
}

// =============================================================================
// Rule: :IUI(path) on DECLARE (W057 / W058 / W059)
// =============================================================================

// FASE 32 / A9 — mirrors Python `_check_iui_paths`.
// Array convention: the array `:IUI` points at the repeated element
// (`…/SUJS/SUJ`); subfields hang from it by name (`…/SUJ[n]/NOMBRE`)
// unless they declare a relative path (`NOMBRE:IUI(PER/NOM)`).
//   W057 — array `:IUI` that can't be applied (subfield paths without
//          an array element path, or `:IUI` inside `:[…]`)
//   W058 — IUI path with fewer than two segments (not for relative
//          subfield paths)
//   W059 — same IUI path on two different variables; for subfields,
//          same resolved relative path twice within one array
function checkIuiPaths(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  const seenPaths = new Map<string, ParsedField>();
  for (const f of fields) {
    const isArray = f.fieldType === FieldType.DECLARE_ARRAY;
    if (f.fieldType !== FieldType.DECLARE && !isArray) continue;
    let hasIui: boolean;
    if (isArray) {
      if (f.iuiIgnored) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W057",
            `DECLARE ARRAY ${f.name}: :IUI(...) dentro de :[…] no se admite — declara la ruta del subcampo como NOMBRE(SUB:IUI(ruta), …); se ignora`),
        );
      }
      const subWithIui = f.arraySubfields.filter((sf) => sf.iuiPath).map((sf) => sf.name);
      if (subWithIui.length > 0 && !f.iuiPath) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W057",
            `DECLARE ARRAY ${f.name}: los subcampos ${subWithIui.join(", ")} tienen :IUI(...) pero el array no declara la ruta de su elemento; se ignoran`),
        );
      }
      if (f.iuiPath) {
        const seenSub = new Map<string, string>();
        for (const sf of f.arraySubfields) {
          const rel = sf.iuiPath || sf.name;
          const key = rel.toUpperCase();
          const prev = seenSub.get(key);
          if (prev !== undefined) {
            result.diagnostics.push(
              diag(f.line, f.col, f.raw.length, Severity.WARNING, "W059",
                `DECLARE ARRAY ${f.name}: el subcampo ${sf.name} usa la ruta IUI '${rel}', que ya usa ${prev}`),
            );
          } else {
            seenSub.set(key, sf.name);
          }
        }
      }
      hasIui = !!f.iuiPath;
    } else {
      hasIui = f.content.toUpperCase().replace(/ /g, "").includes(":IUI(");
    }
    if (!hasIui) continue;
    const kind = isArray ? "DECLARE ARRAY" : "DECLARE";
    const segments = f.iuiPath.split("/").filter((seg) => seg.trim().length > 0);
    if (segments.length < 2) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W058",
          `${kind} ${f.name}: la ruta :IUI(${f.iuiPath}) debe tener al menos dos segmentos (p. ej. DOCS_NOT/DOC_NOT/SUJS/SUJ[1]/PER/NOM)`),
      );
    }
    if (!f.iuiPath) continue;
    const key = f.iuiPath.toUpperCase();
    const first = seenPaths.get(key);
    if (first === undefined) {
      seenPaths.set(key, f);
    } else if (first.name.toUpperCase() !== f.name.toUpperCase()) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W059",
          `${kind} ${f.name}: la ruta IUI '${f.iuiPath}' ya está asignada a ${first.name} (línea ${first.line})`),
      );
    }
  }
}

// =============================================================================
// Rule: W056 — uses without explicit DECLARE
// =============================================================================

// Reserved words inside IF conditions that look like identifiers but
// aren't field names. Without filtering, malformed conditions
// (`IF "x" IN CAMPO` — E013) would bleed `IN` through and W056
// would fire on it as a phantom field.
const IF_RESERVED = new Set([
  "AND", "OR", "NOT", "IN", "IF", "ELSE", "ENDIF", "TRUE", "FALSE",
]);

// Pseudo-fields shaped like directives that the composer always
// strips — never need a DECLARE.
const DIRECTIVE_PSEUDO_FIELDS = new Set([
  "COMMENT_BEGIN", "COMMENT_END",
  "HUMAN_ACTION", "HUMAN_ACTION_PRE", "HUMAN_ACTION_POST",
  "HUMAN_ACTION_INIT", "END_HUMAN_ACTION",
]);

export type IncludeResolver = (target: string) => { content: string } | null;

function composeSuffix(inner: string, outer: string): string {
  if (!outer) return inner;
  if (!inner) return outer;
  return inner + outer;
}

function extractIfFieldRefs(content: string): string[] {
  const trimmed = content.trim();
  const upper = trimmed.toUpperCase();
  if (upper === "ENDIF" || upper === "ELSE") return [];
  if (upper.startsWith("ENDIF_") || upper.startsWith("ENDIF ")) return [];
  let cond: string;
  if (upper.startsWith("IF_") || upper.startsWith("IF ")) cond = trimmed.slice(3);
  else if (upper.startsWith("ELSE_") || upper.startsWith("ELSE ")) cond = trimmed.slice(5);
  else cond = trimmed;
  const noStrings = cond.replace(/"[^"]*"/g, " ").replace(/'[^']*'/g, " ");
  const noLists = noStrings.replace(/\b(?:NOT\s+)?IN\s*\([^)]*\)/gi, "");
  const atoms = noLists.split(/\b(?:AND|OR|NOT)\b|[()]/i);
  const out: string[] = [];
  for (const atom of atoms) {
    const t = atom.trim();
    if (!t) continue;
    const lhs = t.split(/==|!=/)[0].trim();
    const m = lhs.match(/^(SYSTEM:)?([A-Za-z_][\w.\u00C0-\u024F]*)/);
    if (m && !IF_RESERVED.has(m[0].toUpperCase())) out.push(m[0]);
  }
  return out;
}

/**
 * Walk an INCLUDE chain via *resolver*, accumulating declared names +
 * ALLOW_UNDECLARED entries with FIELDS:_xxx suffix application. Returns
 * false if any target couldn't be resolved — caller falls back to the
 * permissive no-INCLUDE path so we don't fire false positives when the
 * editor hasn't loaded a fragment yet.
 */
function walkInclude(
  target: string,
  outerSuffix: string,
  resolver: IncludeResolver,
  declared: Set<string>,
  allowed: Set<string>,
  visited: Set<string>,
): boolean {
  const key = target.toLowerCase();
  if (visited.has(key)) return true;
  visited.add(key);
  const r = resolver(target);
  if (!r) return false;
  const fields = parseFields(r.content);
  let allOk = true;
  for (const f of fields) {
    if (
      (f.fieldType === FieldType.DECLARE ||
        f.fieldType === FieldType.DECLARE_ARRAY ||
        f.fieldType === FieldType.INPUT ||
        f.fieldType === FieldType.INPUT_FINAL) &&
      f.name
    ) {
      declared.add((f.name + outerSuffix).toUpperCase());
    } else if (f.fieldType === FieldType.ALLOW_UNDECLARED) {
      for (const n of f.allowUndeclaredNames) {
        allowed.add((n + outerSuffix).toUpperCase());
      }
    } else if (f.fieldType === FieldType.INCLUDE && f.includeTarget) {
      const composed = composeSuffix(f.includeSuffix || "", outerSuffix);
      if (!walkInclude(f.includeTarget, composed, resolver, declared, allowed, visited)) {
        allOk = false;
      }
    }
  }
  return allOk;
}

/**
 * Collect every DECLARE / DECLARE_ARRAY / INPUT-form name visible from
 * *text* (a master template) plus everything reachable through its
 * INCLUDE chain via *resolver*, with FIELDS:_xxx suffix composition.
 *
 * Use this to pre-seed `extraDeclared` when validating a fragment in
 * the context of its master — the fragment alone wouldn't know about
 * sibling-include declarations.
 */
export function collectAllDeclares(
  text: string,
  resolver: IncludeResolver,
): Set<string> {
  const declared = new Set<string>();
  const allowed = new Set<string>();
  const visited = new Set<string>();
  const fields = parseFields(text);
  for (const f of fields) {
    if (
      (f.fieldType === FieldType.DECLARE ||
        f.fieldType === FieldType.DECLARE_ARRAY ||
        f.fieldType === FieldType.INPUT ||
        f.fieldType === FieldType.INPUT_FINAL) &&
      f.name
    ) {
      declared.add(f.name.toUpperCase());
    } else if (f.fieldType === FieldType.INCLUDE && f.includeTarget) {
      walkInclude(
        f.includeTarget, f.includeSuffix || "",
        resolver, declared, allowed, visited,
      );
    }
  }
  return declared;
}

function checkUndeclaredUses(
  fields: ParsedField[],
  result: ValidationResult,
  resolver?: IncludeResolver,
  extraDeclared?: Iterable<string>,
): void {
  // Build declared / allowed / iter sets from the OPEN file's local fields.
  const declared = new Set<string>();
  // Pre-populate with caller-provided declares — used when a fragment
  // is validated in the context of a master template; the master's
  // sibling-INCLUDE declares cover the fragment's uses.
  if (extraDeclared) for (const n of extraDeclared) declared.add(n);
  const iterVars = new Set<string>();
  const allowed = new Set<string>();
  for (const f of fields) {
    if (
      (f.fieldType === FieldType.DECLARE ||
        f.fieldType === FieldType.DECLARE_ARRAY ||
        f.fieldType === FieldType.INPUT ||
        f.fieldType === FieldType.INPUT_FINAL) &&
      f.name
    ) {
      declared.add(f.name.toUpperCase());
    }
    if (f.fieldType === FieldType.FOR_EACH && f.name) {
      iterVars.add(f.name.toUpperCase());
    }
    if (f.fieldType === FieldType.ALLOW_UNDECLARED) {
      for (const n of f.allowUndeclaredNames) allowed.add(n);
    }
  }

  // Walk INCLUDEs to enrich declared / allowed via the resolver. If
  // any target can't be resolved (or no resolver was provided), we
  // skip the check entirely — declarations may live in the missing
  // fragment and a noisy warning would mislead the user.
  let hasIncludes = false;
  for (const f of fields) {
    if (f.fieldType === FieldType.INCLUDE) { hasIncludes = true; break; }
  }
  if (hasIncludes) {
    if (!resolver) return;
    const visited = new Set<string>();
    for (const f of fields) {
      if (f.fieldType === FieldType.INCLUDE && f.includeTarget) {
        const ok = walkInclude(
          f.includeTarget, f.includeSuffix || "",
          resolver, declared, allowed, visited,
        );
        if (!ok) return;
      }
    }
  }

  const isExempt = (nameUpper: string): boolean => {
    if (nameUpper.startsWith("SYSTEM:")) return true;
    const bare = nameUpper.startsWith("SYSTEM:") ? nameUpper.slice(7) : nameUpper;
    if (Object.prototype.hasOwnProperty.call(SYSTEM_FIELDS, bare)) return true;
    if (DIRECTIVE_PSEUDO_FIELDS.has(nameUpper)) return true;
    // `@autonumber:…` / `@auto:…` tokens parse as EXTRACTED but are
    // post-processed by the composer; they never need a DECLARE.
    if (nameUpper.startsWith("@")) return true;
    const root = nameUpper.split(".")[0];
    if (iterVars.has(root)) return true;
    if (allowed.has(nameUpper)) return true;
    return false;
  };

  const seen = new Set<string>();
  for (const f of fields) {
    const used: string[] = [];
    if (f.fieldType === FieldType.EXTRACTED && f.name) used.push(f.name);
    else if (f.fieldType === FieldType.SET && f.name) used.push(f.name);
    else if (f.fieldType === FieldType.CONDITIONAL) {
      for (const n of extractIfFieldRefs(f.content)) used.push(n);
    }
    for (const name of used) {
      const upper = name.toUpperCase();
      if (isExempt(upper)) continue;
      if (declared.has(upper)) continue;
      const key = `${upper}@${f.line}:${f.col}`;
      if (seen.has(key)) continue;
      seen.add(key);
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.WARNING, "W056",
          `Campo '${name}' usado sin DECLARE explícito`),
      );
    }
  }
}

// =============================================================================
// Rule: Malformed directives
// =============================================================================

// Quote- and paren-aware splitter. Splits `expr` by the boolean
// keyword `sep` ("AND" or "OR") when it appears as a standalone word
// OUTSIDE quoted strings and parenthesised IN(...) lists.
function splitLogicalTop(expr: string, sep: string): string[] {
  const parts: string[] = [];
  let buf: string[] = [];
  let quote: string | null = null;
  let parenDepth = 0;
  const sepUp = sep.toUpperCase();
  let i = 0;
  while (i < expr.length) {
    const c = expr[i];
    if (quote !== null) {
      buf.push(c);
      if (c === quote) quote = null;
      i++; continue;
    }
    if (c === "'" || c === '"') { quote = c; buf.push(c); i++; continue; }
    if (c === "(") { parenDepth++; buf.push(c); i++; continue; }
    if (c === ")") { if (parenDepth > 0) parenDepth--; buf.push(c); i++; continue; }
    if (parenDepth === 0 && /\s/.test(c)) {
      let j = i + 1;
      while (j < expr.length && /\s/.test(expr[j])) j++;
      if (expr.slice(j, j + sepUp.length).toUpperCase() === sepUp) {
        const k = j + sepUp.length;
        if (k >= expr.length || /\s/.test(expr[k])) {
          parts.push(buf.join("").trim());
          buf = [];
          i = k;
          continue;
        }
      }
    }
    buf.push(c);
    i++;
  }
  parts.push(buf.join("").trim());
  return parts;
}

const IF_QUOTE_CHARS = "'\"\u201c\u201d\u00ab\u00bb";

// Quote-aware check that *atom* is a syntactically valid
// `CAMPO [NOT] IN (...)` expression. Tolerates parens / commas inside
// quoted list values (e.g. `"Tres (3)"` or `"a, b"`).
function parseInAtomForValidation(atom: string): boolean {
  const m = atom.match(/^((?:SYSTEM:)?[\w.\u00C0-\u024F]+)\s+(NOT\s+)?IN\s*\(/i);
  if (!m) return false;
  const start = m[0].length;
  let quote: string | null = null;
  for (let i = start; i < atom.length; i++) {
    const c = atom[i];
    if (quote !== null) {
      if (c === quote) quote = null;
      continue;
    }
    if (IF_QUOTE_CHARS.includes(c)) { quote = c; continue; }
    if (c === ")") {
      const body = atom.slice(start, i).trim();
      const tail = atom.slice(i + 1).trim();
      return tail === "" && body !== "";
    }
  }
  return false;
}

function isValidIfAtom(atom: string): boolean {
  const upper = atom.trim().toUpperCase();
  if (!upper) return false;
  // Reserved boolean keywords aren't valid field names on their own.
  if (upper === "NOT" || upper === "AND" || upper === "OR") return false;
  if (/^(?:SYSTEM:)?[\w.\u00C0-\u024F]+(\s*[!=]=\s*(["'\u201c\u201d\u00ab\u00bb][^"'\u201c\u201d\u00ab\u00bb]*["'\u201c\u201d\u00ab\u00bb]|\S+))?\s*$/.test(upper)) return true;
  if (parseInAtomForValidation(atom.trim())) return true;
  // ⚠️ PARCHE A MANO — NO QUITAR AL REGENERAR CON gen-ts.py.
  // Comparaciones numéricas (`<=`, `>=`, `<`, `>`): el lenguaje las acepta
  // desde el 3-oct-2026. Antes daban `E013` y la condición no protegía nada —
  // los 7 esquemas de cancelaciones BS. Ver `src/syntax/comparar.ts`.
  if (parseComparacionParaValidar(atom.trim())) return true;
  return false;
}

// ⚠️ PARCHE A MANO — NO QUITAR AL REGENERAR CON gen-ts.py.
// Se envuelve para no importar el módulo entero en la capa generada.
function parseComparacionParaValidar(atom: string): boolean {
  const c = parseComparacion(atom);
  if (c === null) return false;
  // El literal tiene que ser un número: `{{IF X <= mucho}}` no es válido.
  return parseNumero(c.literal) !== null;
}

function isValidIfExpression(expr: string): boolean {
  const e = expr.trim();
  if (!e) return false;
  const orParts = splitLogicalTop(e, "OR");
  if (orParts.length > 1) return orParts.every(isValidIfExpression);
  const andParts = splitLogicalTop(e, "AND");
  if (andParts.length > 1) return andParts.every(isValidIfExpression);
  if (/^NOT\s+/i.test(e)) return isValidIfExpression(e.slice(3).trim());
  return isValidIfAtom(e);
}

function checkMalformedDirectives(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType !== FieldType.CONDITIONAL) continue;
    const content = f.content.trim();
    const upper = content.toUpperCase();

    // Only check fields that start with IF (not ELSE or ENDIF)
    if (!upper.startsWith("IF")) continue;
    if (upper.startsWith("ENDIF") || upper.startsWith("ELSE")) continue;

    // Strip leading IF (canonical or legacy IF_NAME) and validate the
    // remaining expression as a logical combination of atoms (truthy,
    // ==/!=, IN/NOT IN) joined by AND / OR / NOT (precedence:
    // NOT > AND > OR). Field-name allows optional `SYSTEM:` namespace.
    const mIf = content.match(/^IF(?:_|\s+)([\s\S]*)$/i);
    const expr = mIf ? mIf[1].trim() : "";
    if (expr && isValidIfExpression(expr)) continue;

    // E013: IN / NOT IN with square brackets — suggest parentheses
    // Use a search-style regex so we still catch the form with trailing
    // noise (e.g. :HELP(file)) or an unclosed bracket.
    const mSq = content.match(/IF(?:_|\s+)((?:SYSTEM:)?[\w.\u00C0-\u024F]+)\s+(NOT\s+)?IN\s*\[([^\]]*)\]?/i);
    if (mSq) {
      const fieldName = mSq[1];
      const notPart = (mSq[2] || "").toUpperCase().trim();
      const listBody = mSq[3];
      const op = notPart ? `${notPart} IN` : "IN";
      const d = diag(f.line, f.col, f.raw.length, Severity.ERROR, "E013",
        `Sintaxis IN no soportada con corchetes. Use ${op} (a, b, c) con paréntesis`);
      d.fix = {
        title: "Cambiar corchetes por paréntesis",
        replacement: `{{IF ${fieldName} ${op} (${listBody})}}`,
      };
      result.diagnostics.push(d);
      continue;
    }

    // E014: value comparison with unquoted value that contains spaces
    const mUnquoted = content.match(/^IF(?:_|\s+)((?:SYSTEM:)?[\w\u00C0-\u024F]+)\s*([!=]=)\s*(\S+.*\S)\s*$/i);
    if (mUnquoted) {
      const value = mUnquoted[3];
      if (value.includes(" ")) {
        const d = diag(f.line, f.col, f.raw.length, Severity.ERROR, "E014",
          `Valor con espacios sin comillas. Use {{IF_${mUnquoted[1]}${mUnquoted[2]}'${value}'}}`);
        d.fix = {
          title: "Añadir comillas",
          replacement: `{{IF_${mUnquoted[1]}${mUnquoted[2]}'${value}'}}`,
        };
        result.diagnostics.push(d);
        continue;
      }
    }

    // E013: IF with string literal: {{IF "text" IN FIELD}} or {{IF FIELD IN "text"}}
    if (/IF\s+["'][^"']*["']\s+IN\s+/i.test(upper) ||
        /IF\s+\S+\s+IN\s+["'][^"']*["']/i.test(upper)) {
      result.diagnostics.push(
        diag(f.line, f.col, f.raw.length, Severity.ERROR, "E013",
          "Sintaxis IF no soportada: condiciones con texto literal. Use {{IF CAMPO}} en su lugar"),
      );
      continue;
    }

    // E013: Generic catch for any remaining unsupported IF syntax
    result.diagnostics.push(
      diag(f.line, f.col, f.raw.length, Severity.ERROR, "E013",
        "Sintaxis IF no soportada. Use {{IF CAMPO}}, {{IF_CAMPO}} o {{IF CAMPO=='valor'}}"),
    );
  }
}

// =============================================================================
// Rule: TAGS and SUMMARY must have content
// =============================================================================

function checkTagsSummarySyntax(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  for (const f of fields) {
    if (f.fieldType === FieldType.TAGS) {
      const after = f.content.slice(f.content.indexOf(":") + 1).trim();
      if (!after) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W060",
            "TAGS sin contenido: añada al menos un tag (ej. {{TAGS:contrato, arrendamiento}})"),
        );
      }
    } else if (f.fieldType === FieldType.SUMMARY) {
      const after = f.content.slice(f.content.indexOf(":") + 1).trim();
      if (!after) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W061",
            "SUMMARY sin contenido: añada una descripción (ej. {{SUMMARY:Texto descriptivo}})"),
        );
      }
    }
  }
}

// =============================================================================
// Rule (Phase 7.2): FOR EACH subfield references must match DECLARE ARRAY
// =============================================================================

// Phase 7.2 — E090: {{ITER.SUBFIELD}} referencing a subfield not
// declared in the matching DECLARE ARRAY.
function checkForEachSubfieldReferences(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  const arraySubfields: Record<string, Set<string>> = {};
  for (const f of fields) {
    if (
      f.fieldType === FieldType.DECLARE_ARRAY &&
      f.name &&
      f.arraySubfields &&
      f.arraySubfields.length > 0
    ) {
      arraySubfields[f.name.toUpperCase()] = new Set(
        f.arraySubfields
          .map((sf) => (sf.name || "").toUpperCase())
          .filter((n) => n !== ""),
      );
    }
  }
  if (Object.keys(arraySubfields).length === 0) return;

  const stack: Array<{ iter: string; arr: string }> = [];
  for (const f of fields) {
    if (f.fieldType === FieldType.FOR_EACH) {
      stack.push({
        iter: (f.name || "").toUpperCase(),
        arr: (f.forFieldName || "").toUpperCase(),
      });
      continue;
    }
    if (f.fieldType === FieldType.END_FOR) {
      if (stack.length) stack.pop();
      continue;
    }
    if (f.fieldType !== FieldType.EXTRACTED || !f.name || !f.name.includes(".")) {
      continue;
    }
    const upper = f.name.toUpperCase();
    const dot = upper.indexOf(".");
    const prefix = upper.slice(0, dot);
    const sub = upper.slice(dot + 1);
    for (let i = stack.length - 1; i >= 0; i--) {
      const frame = stack[i];
      if (frame.iter === prefix) {
        const declared = arraySubfields[frame.arr];
        if (declared && sub && !declared.has(sub)) {
          result.diagnostics.push(
            diag(f.line, f.col, f.raw.length, Severity.ERROR, "E090",
              `Subcampo '${sub}' de '${frame.iter}' no declarado en DECLARE ARRAY ${frame.arr}`),
          );
        }
        break;
      }
    }
  }
}

// =============================================================================
// Rule (Phase 7.3): IF comparison type compatibility
// =============================================================================

// Phase 7.3 — E091 / W091: type compatibility on IF comparisons.

function isQuotedStringLiteral(v: string): boolean {
  v = v.trim();
  if (v.length < 2) return false;
  const quotes = "'\"\u201c\u201d\u00ab\u00bb";
  return quotes.includes(v[0]) && quotes.includes(v[v.length - 1]);
}

function isNumericLiteral(v: string): boolean {
  v = v.trim().replace(/^['"\u201c\u201d\u00ab\u00bb]+|['"\u201c\u201d\u00ab\u00bb]+$/g, "");
  if (!v) return false;
  return !Number.isNaN(Number(v));
}

type IfCondition = {
  fieldName: string;
  op: "" | "==" | "!=" | "IN" | "NOT_IN";
  value: string | null;
  inValues: string[] | null;
} | null;

function parseIfCondition(content: string): IfCondition {
  const trimmed = content.trim();
  const upper = trimmed.toUpperCase();
  let cond: string;
  if (upper.startsWith("IF ")) cond = trimmed.slice(3).trim();
  else if (upper.startsWith("IF_")) cond = trimmed.slice(3).trim();
  else return null;

  const notInM = cond.match(/^([\w.\u00C0-\u024F]+)\s+NOT\s+IN\s*\(([^)]+)\)\s*$/i);
  if (notInM) {
    return {
      fieldName: notInM[1],
      op: "NOT_IN",
      value: null,
      inValues: notInM[2].split(",").map((v) => v.trim()),
    };
  }
  const inM = cond.match(/^([\w.\u00C0-\u024F]+)\s+IN\s*\(([^)]+)\)\s*$/i);
  if (inM) {
    return {
      fieldName: inM[1],
      op: "IN",
      value: null,
      inValues: inM[2].split(",").map((v) => v.trim()),
    };
  }
  if (cond.includes("==")) {
    const idx = cond.indexOf("==");
    return {
      fieldName: cond.slice(0, idx).trim(),
      op: "==",
      value: cond.slice(idx + 2).trim(),
      inValues: null,
    };
  }
  if (cond.includes("!=")) {
    const idx = cond.indexOf("!=");
    return {
      fieldName: cond.slice(0, idx).trim(),
      op: "!=",
      value: cond.slice(idx + 2).trim(),
      inValues: null,
    };
  }
  return { fieldName: cond.trim(), op: "", value: null, inValues: null };
}

function checkIfTypeCompatibility(
  fields: ParsedField[],
  result: ValidationResult,
): void {
  const types: Record<string, string> = {};
  for (const f of fields) {
    if (
      (f.fieldType === FieldType.DECLARE || f.fieldType === FieldType.DECLARE_ARRAY) &&
      f.name &&
      f.declareType
    ) {
      types[f.name.toUpperCase()] = f.declareType;
    }
  }
  if (Object.keys(types).length === 0) return;

  for (const f of fields) {
    if (f.fieldType !== FieldType.CONDITIONAL) continue;
    const parsed = parseIfCondition(f.content);
    if (!parsed) continue;
    const declType = types[parsed.fieldName.toUpperCase()];
    if (!declType) continue;

    if (declType === "NUM") {
      const offenders: string[] = [];
      if ((parsed.op === "==" || parsed.op === "!=") && parsed.value !== null) {
        if (!isNumericLiteral(parsed.value)) offenders.push(parsed.value);
      } else if ((parsed.op === "IN" || parsed.op === "NOT_IN") && parsed.inValues) {
        for (const v of parsed.inValues) {
          if (!isNumericLiteral(v)) offenders.push(v);
        }
      }
      for (const off of offenders) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.ERROR, "E091",
            `Comparación de campo NUM '${parsed.fieldName}' con literal no numérico: ${off}`),
        );
      }
    } else if (declType === "BOOL") {
      const isViolation = (v: string): boolean => {
        const stripped = v.trim().replace(/^['"\u201c\u201d\u00ab\u00bb]+|['"\u201c\u201d\u00ab\u00bb]+$/g, "").toUpperCase();
        return stripped !== "TRUE" && stripped !== "FALSE";
      };
      const offenders: string[] = [];
      if ((parsed.op === "==" || parsed.op === "!=") && parsed.value !== null) {
        if (isViolation(parsed.value)) offenders.push(parsed.value);
      } else if ((parsed.op === "IN" || parsed.op === "NOT_IN") && parsed.inValues) {
        for (const v of parsed.inValues) {
          if (isViolation(v)) offenders.push(v);
        }
      }
      for (const off of offenders) {
        result.diagnostics.push(
          diag(f.line, f.col, f.raw.length, Severity.WARNING, "W091",
            `Comparación de campo BOOL '${parsed.fieldName}' con valor que no es TRUE/FALSE: ${off}`),
        );
      }
    }
  }
}

// =============================================================================
// Main entry point (single-file, in-editor validation)
// =============================================================================

export function validateText(
  text: string,
  resolver?: IncludeResolver,
  extraDeclared?: Iterable<string>,
): ValidationResult {
  const result: ValidationResult = {
    diagnostics: [],
    fieldsFound: 0,
  };

  const fields = parseFields(text);
  result.fieldsFound = fields.length;

  // Run all per-file checks
  checkSyntaxErrors(text, result);
  checkTypos(text, result);
  checkBalancedConditionals(fields, result);
  checkLegacyConditionalForm(fields, result);
  checkIncludeForm(fields, result);
  checkIncludeNombreCortado(fields, result);
  if (resolver) checkIncludeDestinoExiste(fields, resolver, result);
  checkCommentBlockForm(fields, result);
  checkInputSyntax(fields, result);
  checkDependencySyntax(fields, result);

  // AUTO checks: collect ALL field names for hint validation (placeholders
  // AND declared names). An `AUTO(FOO)` whose hint points at a DECLAREd-
  // but-never-placeheld field is still legit, so EXTRACTED-only would
  // produce false W041s. Cross-include declarations also count, via
  // the caller-supplied `extraDeclared`.
  const fieldNames = new Set<string>();
  for (const f of fields) {
    if (
      f.name &&
      (f.fieldType === FieldType.EXTRACTED ||
        f.fieldType === FieldType.DECLARE ||
        f.fieldType === FieldType.DECLARE_ARRAY ||
        f.fieldType === FieldType.INPUT ||
        f.fieldType === FieldType.INPUT_FINAL)
    ) {
      fieldNames.add(f.name.toUpperCase());
    }
  }
  if (extraDeclared) for (const n of extraDeclared) fieldNames.add(n);
  checkAutoSyntax(fields, fieldNames, result);
  checkDuplicateDefinitions(fields, result);
  checkDeclareSyntax(fields, result);
  checkIuiPaths(fields, result);
  checkUndeclaredUses(fields, result, resolver, extraDeclared);
  checkMalformedDirectives(fields, result);
  checkTagsSummarySyntax(fields, result);
  checkForEachSubfieldReferences(fields, result);
  checkIfTypeCompatibility(fields, result);

  // Sort by line, then col
  result.diagnostics.sort((a, b) => a.line - b.line || a.col - b.col);

  return result;
}
